name: Test Deploy parrot-devtools to Chrome Webstore

# only trigger on pull request closed events
on:
  pull_request_review_comment:
    types: [created]
jobs:
  deploy_job:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run deploy script
        run: ls -la
