name: Test Deploy parrot-devtools to Chrome Webstore

# only trigger on pull request closed events
on: issue_comment
jobs:
  deploy_job:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM packages
        run: npm install
        working-directory: packages/parrot-devtools
      - name: Run deploy script
        working-directory: packages/parrot-devtools
        env:
          CHROME_WEBSTORE_ACCESS_TOKEN: ${{ secrets.CHROME_WEBSTORE_ACCESS_TOKEN }}
          CHROME_WEBSTORE_CLIENT_ID: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          CHROME_WEBSTORE_CLIENT_SECRET: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          CHROME_WEBSTORE_PARROT_DEVTOOLS_APP_ID: ${{ secrets.CHROME_WEBSTORE_PARROT_DEVTOOLS_APP_ID }}
        run: npm run deploy:extension
