name: Test Deploy parrot-devtools to Chrome Webstore

# only trigger on pull request closed events
on:
  pull_request_review_comment:
    types: [created]
    paths:
      - 'packages/parrot-devtools/src/browser/extension'
      - 'packages/parrot-devtools/src/browser/views/extension'

jobs:
  deploy_job:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    steps:
    - run: |
        cd packages/parrot-devtools
        npm run deploy:extension
